//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS_App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HMS_App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _203114_removebg_preview_1_ {
            get {
                object obj = ResourceManager.GetObject("203114-removebg-preview(1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _203114_removebg_preview_1_1 {
            get {
                object obj = ResourceManager.GetObject("203114-removebg-preview(1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2137982_removebg_preview_1_ {
            get {
                object obj = ResourceManager.GetObject("2137982-removebg-preview(1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2137982_removebg_preview_1_1 {
            get {
                object obj = ResourceManager.GetObject("2137982-removebg-preview(1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5912669_removebg_preview_1_ {
            get {
                object obj = ResourceManager.GetObject("5912669-removebg-preview(1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5912669_removebg_preview_1_1 {
            get {
                object obj = ResourceManager.GetObject("5912669-removebg-preview(1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddMedicine_removebg_preview_1_ {
            get {
                object obj = ResourceManager.GetObject("AddMedicine_removebg_preview_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Addpatient_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Addpatient-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Addpatient_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("Addpatient-removebg-preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background12 {
            get {
                object obj = ResourceManager.GetObject("background12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background121 {
            get {
                object obj = ResourceManager.GetObject("background121", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background122 {
            get {
                object obj = ResourceManager.GetObject("background122", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background123 {
            get {
                object obj = ResourceManager.GetObject("background123", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Banner_1 {
            get {
                object obj = ResourceManager.GetObject("Banner_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bed_Availibility_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Bed_Availibility_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BookAppointment_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("BookAppointment_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Check_Doctor_Schedule_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Check_Doctor_Schedule_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBill_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("CheckBill_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeleteMed {
            get {
                object obj = ResourceManager.GetObject("DeleteMed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DemandMed_removebg_preview_1_ {
            get {
                object obj = ResourceManager.GetObject("DemandMed_removebg_preview_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap discharge_icon_12_removebg_preview_1_ {
            get {
                object obj = ResourceManager.GetObject("discharge-icon-12-removebg-preview(1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap discharge_icon_12_removebg_preview_1_1 {
            get {
                object obj = ResourceManager.GetObject("discharge-icon-12-removebg-preview(1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap discharge_icon_12_removebg_preview_1_2 {
            get {
                object obj = ResourceManager.GetObject("discharge-icon-12-removebg-preview(1)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap discharge_icon_12_removebg_preview_1_3 {
            get {
                object obj = ResourceManager.GetObject("discharge-icon-12-removebg-preview(1)3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExpiredMed1_transformed_removebg_preview_1_ {
            get {
                object obj = ResourceManager.GetObject("ExpiredMed1_transformed_removebg_preview_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hospital {
            get {
                object obj = ResourceManager.GetObject("Hospital", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hospital1 {
            get {
                object obj = ResourceManager.GetObject("Hospital1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hospital2 {
            get {
                object obj = ResourceManager.GetObject("Hospital2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hospital3 {
            get {
                object obj = ResourceManager.GetObject("Hospital3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images_removebg_preview_1_ {
            get {
                object obj = ResourceManager.GetObject("images-removebg-preview(1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_492028_1_ {
            get {
                object obj = ResourceManager.GetObject("img_492028(1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Invoice_1_ {
            get {
                object obj = ResourceManager.GetObject("Invoice(1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Invoice_1__removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Invoice_1_-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MedicalReport_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("MedicalReport_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Patient_Detail_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Patient_Detail_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap patientInfo_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("patientInfo-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap patientInfo_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("patientInfo-removebg-preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap patientMenu {
            get {
                object obj = ResourceManager.GetObject("patientMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PatientMenu2 {
            get {
                object obj = ResourceManager.GetObject("PatientMenu2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PatientSatisfactorySurvey_removebg_preview_1_ {
            get {
                object obj = ResourceManager.GetObject("PatientSatisfactorySurvey_removebg_preview_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pharmacy {
            get {
                object obj = ResourceManager.GetObject("Pharmacy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PurchaseMedicine_removebg_preview_1_ {
            get {
                object obj = ResourceManager.GetObject("PurchaseMedicine_removebg_preview_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap roomInfo_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("roomInfo-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap update_account_line_icon_update_account_line_icon_outline_vector_sign_linear_style_pictogram_isolated_white_refresh_user_symbol_103844490_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("update-account-line-icon-update-account-line-icon-outline-vector-sign-linear-styl" +
                        "e-pictogram-isolated-white-refresh-user-symbol-103844490-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap update_account_line_icon_update_account_line_icon_outline_vector_sign_linear_style_pictogram_isolated_white_refresh_user_symbol_103844490_removebg_preview_1_ {
            get {
                object obj = ResourceManager.GetObject("update-account-line-icon-update-account-line-icon-outline-vector-sign-linear-styl" +
                        "e-pictogram-isolated-white-refresh-user-symbol-103844490-removebg-preview(1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap update_account_line_icon_update_account_line_icon_outline_vector_sign_linear_style_pictogram_isolated_white_refresh_user_symbol_103844490_removebg_preview_1_1 {
            get {
                object obj = ResourceManager.GetObject("update-account-line-icon-update-account-line-icon-outline-vector-sign-linear-styl" +
                        "e-pictogram-isolated-white-refresh-user-symbol-103844490-removebg-preview(1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap update_account_line_icon_update_account_line_icon_outline_vector_sign_linear_style_pictogram_isolated_white_refresh_user_symbol_103844490_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("update-account-line-icon-update-account-line-icon-outline-vector-sign-linear-styl" +
                        "e-pictogram-isolated-white-refresh-user-symbol-103844490-removebg-preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap update_account_line_icon_update_account_line_icon_outline_vector_sign_linear_style_pictogram_isolated_white_refresh_user_symbol_103844490_removebg_preview2 {
            get {
                object obj = ResourceManager.GetObject("update-account-line-icon-update-account-line-icon-outline-vector-sign-linear-styl" +
                        "e-pictogram-isolated-white-refresh-user-symbol-103844490-removebg-preview2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UpdateMedicine_removebg_preview_1_ {
            get {
                object obj = ResourceManager.GetObject("UpdateMedicine_removebg_preview_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_remove_line_icon_user_remove_line_icon_outline_vector_sign_linear_style_pictogram_isolated_white_delete_account_symbol_103844356_removebg_preview_1_ {
            get {
                object obj = ResourceManager.GetObject("user-remove-line-icon-user-remove-line-icon-outline-vector-sign-linear-style-pict" +
                        "ogram-isolated-white-delete-account-symbol-103844356-removebg-preview(1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_remove_line_icon_user_remove_line_icon_outline_vector_sign_linear_style_pictogram_isolated_white_delete_account_symbol_103844356_removebg_preview_1_1 {
            get {
                object obj = ResourceManager.GetObject("user-remove-line-icon-user-remove-line-icon-outline-vector-sign-linear-style-pict" +
                        "ogram-isolated-white-delete-account-symbol-103844356-removebg-preview(1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_remove_line_icon_user_remove_line_icon_outline_vector_sign_linear_style_pictogram_isolated_white_delete_account_symbol_103844356_removebg_preview_1_2 {
            get {
                object obj = ResourceManager.GetObject("user-remove-line-icon-user-remove-line-icon-outline-vector-sign-linear-style-pict" +
                        "ogram-isolated-white-delete-account-symbol-103844356-removebg-preview(1)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap View_Common_Diseases_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("View_Common_Diseases_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap View_Medicines_removebg_preview_1_ {
            get {
                object obj = ResourceManager.GetObject("View_Medicines_removebg_preview_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap View_Prescription_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("View_Prescription_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Xl_TFPJbHkpzqns12DVi5_transformed_removebg_preview_1_ {
            get {
                object obj = ResourceManager.GetObject("Xl_TFPJbHkpzqns12DVi5-transformed-removebg-preview(1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Xl_TFPJbHkpzqns12DVi5_transformed_removebg_preview_1_1 {
            get {
                object obj = ResourceManager.GetObject("Xl_TFPJbHkpzqns12DVi5-transformed-removebg-preview(1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
